AWSTemplateFormatVersion: 2010-09-09
Description: personal-rds

Resources:
  MyDbSecurityByCIDRIPGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      GroupDescription: Ingress for CIDRIP
      DBSecurityGroupIngress:
        CIDRIP: "172.16.0.0/16"
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSecurityGroups:
        - Ref: MyDbSecurityByCIDRIPGroup
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.small
      Engine: MySQL
      LicenseModel: bring-your-own-license
      MasterUsername: master
      MasterUserPassword: SecretPassword01
    DeletionPolicy: Snapshot